# action.yml
name: 'randomrepo'
description: 'Fetch name of a random GitHub repository'
branding:
  icon: 'search'  
  color: 'yello'
inputs:
  github-token:
    description: 'Token used to login to GitHub'
    required: true
outputs:
  repo:
    description: 'Name of random repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.github-token }}
